<a href="https://colab.research.google.com/github/phtevegibson/COMP527-colabNotebooks/blob/main/Numpy%2C_Matplotlib%2C_and_Math_Preliminaries.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy, Matplotlib and Math preliminaries

Numpy is a python library that provides data structures useful for data mining such as arrays, and various functions on those data structures. Follow [the official numpy tutorial](https://numpy.org/devdocs/user/quickstart.html) and familiarize yourself with numpy. Using only Numpy as an external library complete the following exercises.


In [2]:
import numpy as np


## Excercise 1
Given $\overline{X} = (1,2,3,4,5,6,7,8,9,10)^T$ and $\overline{Y} = (10,9,8,7,6,5,4,3,2,1)^T$ find

1. $\overline{X} + \overline{Y}$
2. $\overline{X}^T \overline{Y}$
2. $\overline{X}\overline{Y}^T$


In [4]:
X = np.transpose(np.array([1,2,3,4,5,6,7,8,9,10]))
Y = np.transpose(np.array([10,9,8,7,6,5,4,3,2,1]))

In [5]:
# 1
X + Y

array([11, 11, 11, 11, 11, 11, 11, 11, 11, 11])

In [20]:
# 2
np.transpose(X) @ Y

220

In [19]:
# 3
X @ np.transpose(Y)

220

---
## Excercise 2
Given two matrices 
$\overline{A} = \begin{pmatrix}1 & 2 & 3 & 4 & 5\\ 6 & 7 & 8 & 9 & 10\\ 11 & 12 & 13 & 14 & 15\\ 16 & 17 & 18 & 19 & 20\\ 21 & 22 & 23 & 24 & 25 \end{pmatrix}$
and 
$\overline{B} = \begin{pmatrix}0 & 1 & 0 & 1 & 0\\ 1 & 2 & 3 & 4 & 5\\ -1 & 0 & 1 & 0 & -1 \\ 5 & 4 & 3 & 2 & 5\\ -1 & 0 & 1 & 0 & -1 \end{pmatrix}$

1. Compute $\overline{A} + \overline{B}$
2. Compute $\overline{B} + \overline{A}$. Is it equal to $\overline{A} + \overline{B}$? Is it always the case?
3. Compute $\overline{A} \cdot \overline{B}$
4. Compute $\overline{B} \cdot \overline{A}$. Is it equal to $\overline{A} \cdot \overline{B}$?

the last axis is printed from left to right,

the second-to-last is printed from top to bottom,

the rest are also printed from top to bottom, with each slice separated from the next by an empty line.

In [17]:
A = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
B = np.array([[0,1,0,1,0],[1,2,3,4,5],[-1,0,1,0,-1],[5,4,3,2,5],[-1,0,1,0,-1]])
print(f'A:\n{A}\n\nB:\n{B}')

A:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

B:
[[ 0  1  0  1  0]
 [ 1  2  3  4  5]
 [-1  0  1  0 -1]
 [ 5  4  3  2  5]
 [-1  0  1  0 -1]]


In [11]:
# 1
A + B

array([[ 1,  3,  3,  5,  5],
       [ 7,  9, 11, 13, 15],
       [10, 12, 14, 14, 14],
       [21, 21, 21, 21, 25],
       [20, 22, 24, 24, 24]])

In [12]:
# 2
B + A

array([[ 1,  3,  3,  5,  5],
       [ 7,  9, 11, 13, 15],
       [10, 12, 14, 14, 14],
       [21, 21, 21, 21, 25],
       [20, 22, 24, 24, 24]])

In [18]:
# 3
# * does elementwise multiplication only
# @ or dot method does matrix multiplication
A @ B

array([[ 14,  21,  26,  17,  22],
       [ 34,  56,  66,  52,  62],
       [ 54,  91, 106,  87, 102],
       [ 74, 126, 146, 122, 142],
       [ 94, 161, 186, 157, 182]])

In [21]:
# 4
B @ A

array([[ 22,  24,  26,  28,  30],
       [215, 230, 245, 260, 275],
       [-11, -12, -13, -14, -15],
       [199, 218, 237, 256, 275],
       [-11, -12, -13, -14, -15]])

---
## Excercise 3
Compute the inverse of the following matrix
$\overline{A} = \begin{pmatrix} 1 & 2 & 4\\ -2 & 1 & 5 \\1 & 2 & 3 \end{pmatrix}$, if one exsits. Verify that the matrix product of $\overline{A}$ and its inverse is the 3x3 identity matrix. 

---
## Excercise 4
Find the ranks of the following matrices
$\overline{A} = \left(\begin{matrix} 1 & 0 & 1 \\ 0 & 1 & 1\\ 0 & 0 & 0\end{matrix}\right)~$ and
$~\overline{B} = \left(\begin{matrix} 1 & 2 & 1 \\-2 & -3 & 1\\ 3 & 5 & 0\end{matrix}\right)$.

---
## Excercise 5
Find the eigenvalues of matrix
 $\overline{A} = \left(\begin{matrix} 4 & 2\\ 1 & 3\end{matrix}\right)$

---
## Excercise 6
 
For this excercise we will need [Matplotlib](https://matplotlib.org/index.html). Follow [the official Matplotlib tutorial](https://matplotlib.org/tutorials/introductory/pyplot.html#) and familiarize yourself with Matplotlib.

Recall from the lecture the Gradient Descent method for finding local minimum of a function:

1. Pick an initial point $\overline{X}_0$
2. Iterate according to $\overline{X}_{i+1} = \overline{X}_i - \gamma \cdot \big((\nabla_{\overline{X}} f)(\overline{X}_i) \big)$


Examine this method by trying to find the minimum of the function $f(x) = (x-3)^2$. More specifically, for every $\gamma \in \{0.01, 0.1, 0.9, 1, 2\}$:
1. Plot the graph of $f(x) = (x-3)^2$
2. Pick an intial point $x = -4$
3. Run 20 interations of the methods 
4. In every iteration $i = 1, \ldots, 20$, plot the point $(x_i, f(x_i))$ on the same plot as the graph of the function $f(x)$

Interpret the results.

In [ ]:
import matplotlib.pyplot as plt